# Generated by Django 3.0.5 on 2020-05-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200505_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='blankProfile.jpg', upload_to='profile_pics'),
        ),
    ]
