# Generated by Django 3.0.4 on 2020-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200331_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_profile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
