# Generated by Django 3.0.4 on 2020-05-03 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0003_auto_20200501_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postUserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='postUserID', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='blankProfile.jpg', upload_to='profile_pics')),
                ('description', models.TextField(blank=True)),
                ('likeOption', models.CharField(choices=[('Like', 'Dislike'), ('Like', 'Dislike')], max_length=7)),
            ],
        ),
    ]
