# Generated by Django 3.0.4 on 2020-04-07 02:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_accounts_profile_hobbies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accounts_profile',
            new_name='UserProfile',
        ),
    ]
