# Generated by Django 3.0.4 on 2020-05-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
