# Generated by Django 3.0.4 on 2020-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200430_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
