# Generated by Django 3.0.4 on 2020-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='memberOfTribe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
