# Generated by Django 3.0.5 on 2020-05-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_memberoftribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dislikes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
