# Generated by Django 3.0.4 on 2020-05-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
