# Generated by Django 3.0.4 on 2020-05-01 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('tribeID', models.IntegerField(primary_key=True, serialize=False)),
                ('tribeName', models.CharField(max_length=50)),
                ('dateOfCreation', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=30)),
                ('privacyMode', models.CharField(choices=[('Public', 'Private'), ('Private', 'Public')], default='Private', max_length=7)),
                ('numOfMembers', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('tribeOwner', models.CharField(max_length=50)),
            ],
        ),
    ]
