# Generated by Django 3.0.4 on 2020-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('tribeID', models.IntegerField(primary_key=True, serialize=False)),
                ('tribeName', models.CharField(max_length=50)),
                ('dateOfCreation', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('numOfMembers', models.IntegerField()),
                ('tribeOwner', models.CharField(max_length=50)),
            ],
        ),
    ]
