# Generated by Django 3.0.4 on 2020-05-05 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('tribeID', models.IntegerField(primary_key=True, serialize=False)),
                ('tribeName', models.CharField(max_length=50)),
                ('dateOfCreation', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=30)),
                ('privacyMode', models.CharField(choices=[('Public', 'Private'), ('Private', 'Public')], default='Private', max_length=7)),
                ('numOfMembers', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('tribeOwner', models.CharField(max_length=50)),
                ('tribeMembers', models.ManyToManyField(related_name='tribeMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('houseName', models.CharField(default='', max_length=200)),
                ('houseID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateOfCreation', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('houseCreator', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tribeID', models.ManyToManyField(default=0, to='tribes.Tribe')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(default='', max_length=200)),
                ('postTribeID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tribes.Tribe')),
                ('image', models.ImageField(default='blankProfile.jpg', upload_to='profile_pics')),
                ('description', models.TextField(blank=True)),
                ('dateOfCreation', models.DateField(default=django.utils.timezone.now)),
                ('tribePosterID', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('tribeIDToJoin', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tribes.Tribe')),
                ('requestMessage', models.TextField(default='', max_length=300)),
                ('requestingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('tribeEvent', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tribes.Tribe')),
                ('requestMessage', models.TextField(default='', max_length=300)),
                ('image', models.ImageField(default='blankProfile.jpg', upload_to='profile_pics')),
                ('description', models.TextField(blank=True)),
                ('dateOfCreation', models.DateField(default=django.utils.timezone.now)),
                ('postingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
