# Generated by Django 3.0.4 on 2020-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='privacyMode',
            field=models.CharField(choices=[('Public', 'Private'), ('Private', 'Public')], default='Private', max_length=7),
        ),
    ]
