# Generated by Django 3.0.4 on 2020-05-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='tribeIDToJoin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tribes.Tribe'),
        ),
    ]
