# Generated by Django 3.0.4 on 2020-05-03 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dateOfCreation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
