# Generated by Django 3.0.4 on 2020-04-07 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_auto_20200406_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='dateOfCreation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='numOfMembers',
            field=models.IntegerField(default=1),
        ),
    ]
