# Generated by Django 3.0.5 on 2020-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_auto_20200505_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=298, primary_key=True, serialize=False),
        ),
    ]
