# Generated by Django 3.0.4 on 2020-05-05 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tribes', '0002_auto_20200505_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='tribeID',
        ),
        migrations.AddField(
            model_name='house',
            name='tribeIDHouse',
            field=models.ManyToManyField(to='tribes.Tribe'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houseCreator',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='houseID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
