# Generated by Django 3.0.4 on 2020-04-30 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tribes', '0003_auto_20200406_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='tribeOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
