# Generated by Django 3.0.4 on 2020-05-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0003_auto_20200505_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='tribeIDHouse',
            new_name='houseInTribe',
        ),
    ]
