# Generated by Django 3.0.4 on 2020-05-04 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tribes', '0003_posts_dateofcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='tribeMembers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
