# Generated by Django 3.0.4 on 2020-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0004_auto_20200430_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='tribeOwner',
            field=models.CharField(max_length=50),
        ),
    ]
