# Generated by Django 3.0.4 on 2020-05-05 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tribes', '0004_auto_20200505_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=640, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='postTribeID',
        ),
        migrations.AddField(
            model_name='posts',
            name='postTribeID',
            field=models.ManyToManyField(related_name='postTribeID', to='tribes.Tribe'),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tribePosterID',
        ),
        migrations.AddField(
            model_name='posts',
            name='tribePosterID',
            field=models.ManyToManyField(related_name='tribePosterID', to=settings.AUTH_USER_MODEL),
        ),
    ]
