# Generated by Django 3.0.4 on 2020-04-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0005_auto_20200430_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribe',
            name='tribeOwner',
        ),
    ]
