# Generated by Django 3.0.5 on 2020-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0005_auto_20200505_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=489, primary_key=True, serialize=False),
        ),
    ]
