# Generated by Django 3.0.4 on 2020-04-30 23:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0006_remove_tribe_tribeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='tribeOwner',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
