# Generated by Django 3.0.5 on 2020-05-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0006_auto_20200505_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='houseID',
            field=models.IntegerField(default=141, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=221, primary_key=True, serialize=False),
        ),
    ]
