# Generated by Django 3.0.4 on 2020-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0007_tribe_tribeowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='tribeOwner',
            field=models.CharField(max_length=50),
        ),
    ]
